---
name: "commit-lint"

on: "workflow_call"

jobs:
  commit-lint:
    runs-on: "ubuntu-latest"
    container:
      image: "monokera/commitlint"
    steps:
      - name: "checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 0

      - name: "checkout-reusable-workflows"
        uses: "actions/checkout@v2"
        with:
          repository: "monokera-tech/linters-workflow"
          path: "linters-workflow"

      - name: "copy-commitlint-config-file"
        uses: "canastro/copy-action@master"
        with:
          source: "linters-workflow/.commitlintrc.yaml"
          target: ".commitlintrc.yaml"

      - name: "copy-commitlint-scripts"
        uses: "canastro/copy-action@master"
        with:
          source: "linters-workflow/.github/scripts/."
          target: ".github/scripts/"
          flags: "-r"

      - name: "remove-reusable-workflows"
        uses: "JesseTG/rm@v1.0.2"
        with:
          path: "linters-workflow"

      - name: "lint-pr-commits"
        env:
          BRANCH_REF: "${{ github.head_ref }}"
          BRANCH_BASE_REF: "${{ github.base_ref }}"
        run: "sh .github/scripts/lint-pr-commits.sh"
