---
name: "super-lint"

on:
  workflow_call:
    secrets:
      GIT_CRYPT_KEY:
        description: "Required Base64 encoded git-crypt key"
        required: true
      USER_KEY_ID:
        description: "Required *user* gpg key ID for git-crypt"
        required: true
      USER_KEY:
        description: "Required *user* Base64 encoded git-crypt key"
        required: true

jobs:
  git-crypt-add:
    runs-on: "ubuntu-latest"
    if: "startsWith(github.head_ref, 'dependabot') == false"
    steps:
      - name: "checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 0

      - name: "unlock-secrets"
        uses: "acactown/github-action-git-crypt-unlock@master"
        env:
          GIT_CRYPT_KEY: "${{ secrets.GIT_CRYPT_KEY }}"

      - name: "Import key and Add user"
        run: |
          echo "${{ secrets.USER_KEY }}" > user_key.gpg
          gpg --import user_key.gpg
          sudo apt install -y git-crypt
          git-crypt add-gpg-user -n --trusted "${{ secrets.USER_KEY_ID }}"
          rm -rf user_key.gpg

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "Add ${{ secrets.USER_EMAIL }} as git-crypt collaborator"
          branch: "git-crypt/add-${{ secrets.USER_EMAIL }}"
          title: "Add ${{ secrets.USER_EMAIL }} as git-crypt collaborator"
