---
name: "super-lint"

on:
  workflow_call:
    secrets:
      GIT_CRYPT_KEY:
        description: "Required Base64 encoded git-crypt key"
        required: true

jobs:
  super-lint:
    runs-on: "ubuntu-latest"
    if: "startsWith(github.head_ref, 'dependabot') == false"
    steps:
      - name: "checkout"
        uses: "actions/checkout@v3"
        with:
          fetch-depth: 0

      - name: "unlock-secrets"
        uses: "acactown/github-action-git-crypt-unlock@master"
        env:
          GIT_CRYPT_KEY: "${{ secrets.GIT_CRYPT_KEY }}"

      - name: "checkout-reusable-workflows"
        uses: "actions/checkout@v3"
        with:
          repository: "monokera-tech/linters-workflow"
          path: "linters-workflow"

      - name: "copy-linters-config"
        uses: "canastro/copy-file-action@master"
        with:
          source: "linters-workflow/.github/linters/."
          target: ".github/linters/"
          flags: "-r"

      - name: "remove-reusable-workflows"
        uses: "JesseTG/rm@v1.0.2"
        with:
          path: "linters-workflow"

      - name: "super-linter"
        uses: "docker://github/super-linter:slim-v4.8.5"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          DEFAULT_BRANCH: "main"
